create database Nukutaka

USE Nukutaka
GO
CREATE TABLE PRODUCTS(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
NAME NVARCHAR(255),
PRICE INT,
IMAGEURL NVARCHAR(255),
CODECATEGORY VARCHAR(255),
CODEBRAND VARCHAR(255),
CODEKIND VARCHAR(255),
STATUS INT
)

CREATE TABLE CATEGORY(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
NAME NVARCHAR(255)
)

CREATE TABLE BRANDS(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
NAME NVARCHAR(255)
)

CREATE TABLE KIND(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
NAME NVARCHAR(255),
CODECATEGORY VARCHAR(255)
)

CREATE TABLE ADMIN(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
NAME NVARCHAR(255),
PHONE VARCHAR(255),
PASSWORD VARCHAR(255),
)

CREATE TABLE STAFF(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
NAME NVARCHAR(255),
PHONE VARCHAR(255),
)

CREATE TABLE INVOICE(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
NAMECUSTOMER NVARCHAR(255),
PHONECUSTOMER INT,
ADDRESS NVARCHAR(255),
ORDERDATE DATE,
SHIPPINGDATE DATE,
DELIVERYDATE DATE,
STATUS INT
)

CREATE TABLE INVOICE_DETAILS(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
PRODUCT NVARCHAR(MAX)
)

CREATE TABLE TRANSPORT(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
CODEADMIN VARCHAR(255),
CODESTAFF VARCHAR(255),
STARTDATE DATE,
ENDDATE DATE,
STATUS INT
)

INSERT INTO CATEGORY VALUES (1, N'NAM')
INSERT INTO CATEGORY VALUES (2, N'NỮ')
INSERT INTO CATEGORY VALUES (3, N'TRẺ EM')

INSERT INTO KIND VALUES (1, N'Áo sơ mi tay ngắn', 1)
INSERT INTO KIND VALUES (2, N'Áo sơ mi tay dài', 1)
INSERT INTO KIND VALUES (3, N'Áo thun', 2)
INSERT INTO KIND VALUES (4, N'Áo khoác', 2)
INSERT INTO KIND VALUES (5, N'Quần tây', 1)
INSERT INTO KIND VALUES (6, N'Quần kaki', 3)
INSERT INTO KIND VALUES (7, N'Quần short', 3)

INSERT INTO BRANDS VALUES (1, N'NIKE')
INSERT INTO BRANDS VALUES (2, N'ADIDAS')
INSERT INTO BRANDS VALUES (3, N'PUMA')
INSERT INTO BRANDS VALUES (4, N'GUCCI')
INSERT INTO BRANDS VALUES (5, N'CHANEL')

INSERT INTO PRODUCTS VALUES ('SP01', N'SẢN PHẨM 1', 100, 'images/home/product1.jpg', 1, 2, 1, 1)
INSERT INTO PRODUCTS VALUES ('SP02', N'SẢN PHẨM 2', 200, 'images/home/product2.jpg', 1, 5, 2, 1)
INSERT INTO PRODUCTS VALUES ('SP06', N'SẢN PHẨM 3', 300, 'images/home/product3.jpg', 1, 1, 3, 1)
INSERT INTO PRODUCTS VALUES ('SP03', N'SẢN PHẨM 4', 400, 'images/home/product4.jpg', 2, 4, 4, 1)
INSERT INTO PRODUCTS VALUES ('SP04', N'SẢN PHẨM 5', 500, 'images/home/product5.jpg', 2, 3, 5, 1)
INSERT INTO PRODUCTS VALUES ('SP05', N'SẢN PHẨM 6', 600, 'images/home/product6.jpg', 3, 5, 7, 1)