CREATE DATABASE Nukutaka
GO
USE Nukutaka
GO
CREATE TABLE PRODUCTS(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
NAME NVARCHAR(255),
PRICE INT,
IMAGEURL NVARCHAR(255),
CODECATEGORY VARCHAR(255),
CODEBRAND VARCHAR(255),
CODEKIND VARCHAR(255),
INSTOCK INT,
STATUS INT
)

CREATE TABLE CATEGORY(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
NAME NVARCHAR(255)
)

CREATE TABLE BRANDS(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
NAME NVARCHAR(255)
)

CREATE TABLE KIND(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
NAME NVARCHAR(255),
CODECATEGORY VARCHAR(255)
)

CREATE TABLE ADMIN(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
NAME NVARCHAR(255),
PHONE VARCHAR(255),
PASSWORD VARCHAR(255),
)

CREATE TABLE STAFF(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
NAME NVARCHAR(255),
PHONE VARCHAR(255),
)

CREATE TABLE INVOICE(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
NAMECUSTOMER NVARCHAR(255),
PHONECUSTOMER VARCHAR(255),
ADDRESS NVARCHAR(255),
ORDERDATE DATE,
SHIPPINGDATE DATE,
DELIVERYDATE DATE,
SHIPPER VARCHAR(255),
STATUS INT
)

CREATE TABLE INVOICE_DETAILS(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
PRODUCT NVARCHAR(MAX)
)

CREATE TABLE TRANSPORT(
ID INT PRIMARY KEY IDENTITY,
CODE VARCHAR(255),
CODEADMIN VARCHAR(255),
CODESTAFF VARCHAR(255),
STARTDATE DATE,
ENDDATE DATE,
STATUS INT
)

INSERT INTO CATEGORY VALUES (1, N'NAM')
INSERT INTO CATEGORY VALUES (2, N'NỮ')
INSERT INTO CATEGORY VALUES (3, N'TRẺ EM')

INSERT INTO KIND VALUES (1, N'Áo sơ mi tay ngắn', 1)
INSERT INTO KIND VALUES (2, N'Áo sơ mi tay dài', 1)
INSERT INTO KIND VALUES (3, N'Áo thun', 2)
INSERT INTO KIND VALUES (4, N'Áo khoác', 2)
INSERT INTO KIND VALUES (5, N'Quần tây', 1)
INSERT INTO KIND VALUES (6, N'Quần kaki', 3)
INSERT INTO KIND VALUES (7, N'Quần short', 3)

INSERT INTO BRANDS VALUES (1, N'NIKE')
INSERT INTO BRANDS VALUES (2, N'ADIDAS')
INSERT INTO BRANDS VALUES (3, N'PUMA')
INSERT INTO BRANDS VALUES (4, N'GUCCI')
INSERT INTO BRANDS VALUES (5, N'CHANEL')

INSERT INTO PRODUCTS VALUES ('SP01', N'SẢN PHẨM 1', 100000, 'product1.jpg', 1, 2, 1, 0, 0)
INSERT INTO PRODUCTS VALUES ('SP02', N'SẢN PHẨM 2', 200000, 'product2.jpg', 1, 5, 2, 1, 0)
INSERT INTO PRODUCTS VALUES ('SP06', N'SẢN PHẨM 3', 300000, 'product3.jpg', 1, 1, 3, 1, 0)
INSERT INTO PRODUCTS VALUES ('SP03', N'SẢN PHẨM 4', 400000, 'product4.jpg', 2, 4, 4, 1, 0)
INSERT INTO PRODUCTS VALUES ('SP04', N'SẢN PHẨM 5', 500000, 'product5.jpg', 2, 3, 5, 1, 0)
INSERT INTO PRODUCTS VALUES ('SP05', N'SẢN PHẨM 6', 600000, 'product6.jpg', 3, 5, 7, 1, 0)
INSERT INTO PRODUCTS VALUES ('SP07', N'SẢN PHẨM 7', 700000, 'product1.jpg', 1, 2, 1, 1, 0)
INSERT INTO PRODUCTS VALUES ('SP08', N'SẢN PHẨM 8', 80000000, 'product2.jpg', 1, 5, 2, 0, 0)
INSERT INTO PRODUCTS VALUES ('SP09', N'SẢN PHẨM 9', 90000000, 'product3.jpg', 1, 1, 3, 0, 0)
INSERT INTO PRODUCTS VALUES ('SP10', N'SẢN PHẨM 10', 1000000, 'product4.jpg', 2, 4, 4, 1, 1)
INSERT INTO PRODUCTS VALUES ('SP11', N'SẢN PHẨM 11', 550000, 'product5.jpg', 2, 3, 5, 1, 1)
INSERT INTO PRODUCTS VALUES ('SP12', N'SẢN PHẨM 12', 680000, 'product6.jpg', 3, 5, 7, 1, 1)
INSERT INTO PRODUCTS VALUES ('SP13', N'SẢN PHẨM 13', 420000, 'product4.jpg', 2, 4, 4, 0, 0)
INSERT INTO PRODUCTS VALUES ('SP14', N'SẢN PHẨM 14', 580000, 'product5.jpg', 2, 3, 5, 1, 1)
INSERT INTO PRODUCTS VALUES ('SP15', N'SẢN PHẨM 15', 635000, 'product6.jpg', 3, 5, 7, 0, 1)
INSERT INTO PRODUCTS VALUES ('SP16', N'SẢN PHẨM 16', 765000, 'product1.jpg', 1, 2, 1, 0, 0)
INSERT INTO PRODUCTS VALUES ('SP17', N'SẢN PHẨM 17', 80000000, 'product2.jpg', 1, 5, 2, 0, 1)

CREATE PROC SP_INSERT_UPDATE_PRODUCT(@P_ID INT,
									 @P_CODE VARCHAR(255),
									 @P_NAME NVARCHAR(255),
									 @P_PRICE INT,
									 @P_IMAGEURL NVARCHAR(255),
									 @P_CODECATEGORY VARCHAR(255),
									 @P_CODEKIND VARCHAR(255),
									 @P_CODEBRAND VARCHAR(255),
									 @P_STATUS INT,
									 @P_INSTOCK INT)
AS
BEGIN
IF(@P_ID = 0)
	INSERT INTO PRODUCTS (CODE,
						  NAME,
						  PRICE,
						  IMAGEURL,
						  CODECATEGORY,
						  CODEKIND,
						  CODEBRAND,
						  STATUS,
						  INSTOCK)
				  VALUES (@P_CODE,
						  @P_NAME,
						  @P_PRICE,
						  @P_IMAGEURL,
						  @P_CODECATEGORY,
						  @P_CODEKIND,
						  @P_CODEBRAND,
						  @P_STATUS,
						  @P_INSTOCK)
ELSE
	UPDATE PRODUCTS SET CODE = @P_CODE,
						NAME = @P_NAME,
						PRICE = @P_PRICE,
						IMAGEURL = @P_IMAGEURL,
						CODECATEGORY = @P_CODECATEGORY,
						CODEKIND = @P_CODEKIND,
						CODEBRAND = @P_CODEBRAND,
						STATUS = @P_STATUS,
						INSTOCK = @P_INSTOCK
			WHERE ID = @P_ID
END

EXEC SP_INSERT_UPDATE_PRODUCT 0, '1', '1N', 1, '234', '2', '3', '4', 1, 1