//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nukutaka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NAMECUSTOMER { get; set; }
        public Nullable<int> PHONECUSTOMER { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public Nullable<System.DateTime> SHIPPINGDATE { get; set; }
        public Nullable<System.DateTime> DELIVERYDATE { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
