//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nukutaka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<int> PRICE { get; set; }
        public string IMAGEURL { get; set; }
        public string CODECATEGORY { get; set; }
        public string CODEBRAND { get; set; }
        public string CODEKIND { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
