//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nukutaka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORT
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string CODEADMIN { get; set; }
        public string CODESTAFF { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<int> STATUS { get; set; }
    }
}
